### ISSUE TITLE
RFE: Allow avoidance of removing packages ntp,chrony

### ISSUE THREAD

**Issue by kfiresmith** [idiv-biodiversity/ansible-role-systemd-timesyncd#1]
Hi Christian Krause,
First, thanks very much for your Ansible Roles.  Also - I wanted to mention that this role is working well on Ubuntu Focal / 20.04 LTS if you wanted to update your Galaxy distro support details.

On to the RFE:  If we could optionally avoid removing legacy packages crony,ntp via setting of a group var, that seems like it would make this role a bit more flexible in cases where you might want those legacy tools in place.  

If this sounds like a reasonable request and path forward, I could write a PR if you'd prefer for me to work on the change.

Thanks!
 - Kodiak

**Comment by wookietreiber** [comment]
Sure, thanks for the suggestion. Feel free to write up the PRs, both for Ubuntu Focal and for introducing the variable to not force the removal.

**Comment by wookietreiber** [comment]
Fixed in b26c439 and f4b3496.
