### ISSUE TITLE
Default package name

### ISSUE THREAD

**Issue by atisne** [idiv-biodiversity/ansible-role-systemd-timesyncd#9]
The default package name is https://github.com/idiv-biodiversity/ansible-role-systemd-timesyncd/blob/104a2794ae9bb136222af4d3514d5d35510496e5/vars/default.yml#L3

AFAIK (in Debian 12, Ubuntu 22, AlmaLinux 9, OracleLinux 9) timesyncd is installed using the package `systemd-timesyncd`.

What about changing the package default value (rather than add extra distribution var files)?

**Comment by wookietreiber** [comment]
For KISS and DRY, my approach here is to use whatever the most minimal amount of LOC is, based on what's supported in `meta/main.yml`. If you're up for adding support and tests for the others and the LOC gets more minimal, then yes, we can change the default.

**Comment by atisne** [comment]
Well... I plan to use this role with Debian, AlmaLinux and OracleLinux. I already tested it with these distributions. I did it changing only one line (in `vars/default.yml`). Otherwise, I should have added 3 more files.

**Comment by wookietreiber** [comment]
Feel free to contribute the support for those distros including the molecule tests, if you do feel free to change the default.

**Comment by wookietreiber** [comment]
@atisne Note that at some point I'll be merging our current set of systemd roles (journald, networkd, resolved, timesyncd) into a new collection.

**Comment by wookietreiber** [comment]
done and done:

- [Ansible Galaxy](https://galaxy.ansible.com/ui/repo/published/idiv_biodiversity/systemd/)
- [GitHub Repo](https://github.com/idiv-biodiversity/ansible-collection-systemd)
